# Generated by Django 4.2 on 2023-04-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/avatar.svg', null=True, upload_to='users/'),
        ),
    ]
