# Generated by Django 4.2 on 2023-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='seen',
            field=models.CharField(default='no', max_length=10),
            preserve_default=False,
        ),
    ]
