# Generated by Django 4.2 on 2023-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_groupmessage_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='groups/'),
        ),
    ]
