# Generated by Django 4.2 on 2023-04-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='groups/avatar.svg', null=True, upload_to='groups/'),
        ),
    ]
