# Generated by Django 4.2 on 2023-05-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='user1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user2',
            field=models.IntegerField(),
        ),
    ]
