# Generated by Django 4.2 on 2023-05-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_requests_user1_alter_requests_user2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requests',
            new_name='Request',
        ),
    ]
