# Generated by Django 4.2 on 2023-05-03 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_requests_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
