# Generated by Django 4.2 on 2023-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_group_image_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_image_message',
            name='image',
            field=models.ImageField(upload_to='group_images/'),
        ),
    ]
