# Generated by Django 4.2 on 2023-06-15 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_group_image_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_image_message',
            name='seen',
        ),
        migrations.AddField(
            model_name='group_image_message',
            name='seen',
            field=models.ManyToManyField(null=True, related_name='image_seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
