from django.urls import path,include
from . import views
urlpatterns = [
    # path('',views.UserListView.as_view(),name='home'),
    path('',views.home,name='home'),
    path('login/',views.loginUser,name='login_user'),
    path('register/',views.registerUser,name='register_user'),
    path('logout/',views.logoutUser,name='logout'),
    path('profile/<str:pk>/',views.profile,name='profile'),
    path('create-group/',views.create_group,name='create-group'),
    path('requests/',views.requests,name='requests'),
    path('friends/',views.friends,name='friends'),
    path('themes/',views.themes,name='themes'),
    path('group/<str:pk>/',views.group,name='group'),
    path('get_messages/<str:pk>/',views.get_messages,name='get_messages'),
    path('get_chats/',views.get_chats,name='get_chats'),
    path('get_group_status/<int:pk>/',views.get_group_status,name='get_group_status'),
    path('get_groupmessages/<int:pk>/',views.get_group_messages,name='get_group_messages'),
    path('send_message/<str:pk>/',views.send_message,name='send_message'),
    path('send_group_message/<int:pk>/',views.send_group_message,name='send_group_message'),
    path('edit_message/<int:pk>/<str:text>/', views.edit_message, name='edit_message'),
    path('edit_group_message/<int:pk>/<str:text>/',views.edit_group_message,name='edit_group_message'),
    path('delete_messages/',views.delete_messages,name='delete_messages'),
    path('delete_group_messages/',views.delete_group_messages,name='delete_group_messages'),
    path('get_users/',views.get_users,name='get_users'),
    path('update_status/',views.update_status,name='update_status'),
    path('get_status/<str:pk>/',views.get_status,name='get_status'),
    path('get_groups/<int:pk>',views.get_members,name='get_members'),
    path('remove_members/<int:pk>',views.remove_members,name='remove_members'),
    path('add_members/<int:pk>/',views.add_members,name='add_members'),
    path('get_requests/',views.get_requests,name='get_requests'),
    path('send_image/',views.send_image,name='send-image'),
    path('send_group_image/',views.send_group_image,name='send_group_image'),
]